name:                spock20240105
version:             0.1.0.0
github:              "githubuser/spock20240105"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spock20240105#readme>

dependencies:
- base >= 4.7 && < 5
- Spock >= 0.14
- mtl
- text
- wai
- wai-extra
- network
- wai-middleware-static
# - wai-static

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  spock20240105-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spock20240105

tests:
  spock20240105-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spock20240105

extra-deps:
  - Spock-0.14.0.0
  - Spock-core-0.14.0.0
  - reroute-0.6.0.0
  - stm-containers-1.2
  - focus-1.0.1.4
  - stm-hamt-1.2.0.4
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0
  - wai-extra-3.1.7
  # - wai-static
  - wai-middleware-static
  - network

